identifier: m1e15ey19d20ebh4
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: angular-timers
homeFolder: /Users/jithinswathi/GitHub/tool-app/angular-timers
distFolder: ./dist/angular-timers/browser
outDir: /Users/jithinswathi/GitHub/tool-app/angular-timers/dist/static
handle404: ''
allowErrorCollect: false
